### ISSUE TITLE
Repeatable component translations messed up after reordering

### ISSUE THREAD

**Issue by pascalbur** [localazy/strapi-plugin#41]
Hey, we currently have the problem that our translations are completely messed up after we changed the order of our repeatable components inside a collection in Strapi. The non-internationalized fields like images etc are all still correct, but the other fields have the contents of the previous translations. 
Is this a known bug, is there a workaround or is it not supported? 

Strapi Version: 4.12.5
Localazy Strapi Plugin Version: 0.1.18

**Comment by david-vaclavek** [comment]
Hello @pascalbur.

Thanks for contacting us.
First of all, I recommend upgrading to the newest [Localazy Strapi Plugin Version](https://www.npmjs.com/package/@localazy/strapi-plugin/v/0.2.2).

But anyway, this is a known issue.
However, it is not currently solvable due to the technical solution on the side of Strapi.

There is a workaround, which is already described in the [Strapi Plugin documentation](https://localazy.com/docs/strapi/strapi-download-translations#download-to-strapi).

Cite:
> When updating the order of translatable repeatable components in the default entry: If you want to achieve the same order in translated entries, delete the field content (with the repeatable component) and click Start download again. The content will be re-created in the correct order.

I'm closing the issue for now, if the suggested steps won't work for you, we can reopen the issue.

**Comment by david-vaclavek** [comment]
Known issue.
Workaround with suggested steps provided.
